[package]
name = "kk"
version = "0.2.1"
edition = "2024"
rust-version = "1.97"
license = "MIT"
description = "A TUI text editor"
homepage = "https://github.com/sile/kk"
repository = "https://github.com/sile/kk"
readme = "README.md"
keywords = ["editor", "tui", "terminal"]
categories = ["command-line-utilities"]
exclude = ["backlog/"]

[dependencies]
libc = "0.2"
noargs = "0.4"
tuinix = "0.7"
unicode-width = "0.2"

[dev-dependencies]
noprop = "0.2"
termnix = "0.5"
